version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: amcef_api_db
    volumes:
      - ./docker/data/db:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
